Update Setup
use git clone instead of wget

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,5 +1,10 @@
 #!/bin/bash
-mkdir /opt/lxq
-wget -O /opt/lxq/lxq https://raw.githubusercontent.com/aaronstuder/lxq/master/lxq
+
+if ! [ -x "$(command -v git)" ]; then
+  echo 'Error: git is not installed. Please install git.' >&2
+  exit 1
+fi
+git clone https://github.com/aaronstuder/lxq.git /opt/lxq
+
 chmod a+x /opt/lxq/lxq
 export PATH=$PATH:/opt/lxq
